
site_name: Java Spring Boot REST Tutorials
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - toc.integrate

nav:
  - Home: index.md
  - Topics:
      - Layered Architecture:
          - Overview: topics/layered-architecture.md
      - Dependency Injection:
          - Overview: topics/dependency-injection.md
      - DTOs vs Entities:
          - Overview: topics/dtos-vs-entities.md

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences

docs_dir: docs
site_dir: site
