
site_name: Java Spring Boot REST Tutorials
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - toc.integrate

nav:
  - Home: index.md
  - Topics:
      - Layered Architecture: topics/layered-architecture.md

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences

docs_dir: docs
site_dir: site
